blacklist: []
build_space: build_x86
catkin_make_args: []
cmake_args: []
devel_layout: merged
devel_space: devel_x86
extend_path: /opt/ros/kinetic
install: true
install_space: install_x86
isolate_install: false
jobs_args: []
log_space: logs_x86
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
