// Generated by gencpp from file fisheye_camera_matrix/perspective_projectionRequest.msg
// DO NOT EDIT!


#ifndef FISHEYE_CAMERA_MATRIX_MESSAGE_PERSPECTIVE_PROJECTIONREQUEST_H
#define FISHEYE_CAMERA_MATRIX_MESSAGE_PERSPECTIVE_PROJECTIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fisheye_camera_matrix
{
template <class ContainerAllocator>
struct perspective_projectionRequest_
{
  typedef perspective_projectionRequest_<ContainerAllocator> Type;

  perspective_projectionRequest_()
    : x(0.0)
    , y(0.0)  {
    }
  perspective_projectionRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;




  typedef boost::shared_ptr< ::fisheye_camera_matrix::perspective_projectionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fisheye_camera_matrix::perspective_projectionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct perspective_projectionRequest_

typedef ::fisheye_camera_matrix::perspective_projectionRequest_<std::allocator<void> > perspective_projectionRequest;

typedef boost::shared_ptr< ::fisheye_camera_matrix::perspective_projectionRequest > perspective_projectionRequestPtr;
typedef boost::shared_ptr< ::fisheye_camera_matrix::perspective_projectionRequest const> perspective_projectionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fisheye_camera_matrix::perspective_projectionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fisheye_camera_matrix::perspective_projectionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace fisheye_camera_matrix

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::fisheye_camera_matrix::perspective_projectionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fisheye_camera_matrix::perspective_projectionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fisheye_camera_matrix::perspective_projectionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fisheye_camera_matrix::perspective_projectionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fisheye_camera_matrix::perspective_projectionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fisheye_camera_matrix::perspective_projectionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fisheye_camera_matrix::perspective_projectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff8d7d66dd3e4b731ef14a45d38888b6";
  }

  static const char* value(const ::fisheye_camera_matrix::perspective_projectionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff8d7d66dd3e4b73ULL;
  static const uint64_t static_value2 = 0x1ef14a45d38888b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::fisheye_camera_matrix::perspective_projectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fisheye_camera_matrix/perspective_projectionRequest";
  }

  static const char* value(const ::fisheye_camera_matrix::perspective_projectionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fisheye_camera_matrix::perspective_projectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n\
float32 y\n\
";
  }

  static const char* value(const ::fisheye_camera_matrix::perspective_projectionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fisheye_camera_matrix::perspective_projectionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct perspective_projectionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fisheye_camera_matrix::perspective_projectionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fisheye_camera_matrix::perspective_projectionRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FISHEYE_CAMERA_MATRIX_MESSAGE_PERSPECTIVE_PROJECTIONREQUEST_H
