// Generated by gencpp from file fisheye_camera_matrix/perspective_projectionResponse.msg
// DO NOT EDIT!


#ifndef FISHEYE_CAMERA_MATRIX_MESSAGE_PERSPECTIVE_PROJECTIONRESPONSE_H
#define FISHEYE_CAMERA_MATRIX_MESSAGE_PERSPECTIVE_PROJECTIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace fisheye_camera_matrix
{
template <class ContainerAllocator>
struct perspective_projectionResponse_
{
  typedef perspective_projectionResponse_<ContainerAllocator> Type;

  perspective_projectionResponse_()
    : p()  {
    }
  perspective_projectionResponse_(const ContainerAllocator& _alloc)
    : p(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _p_type;
  _p_type p;




  typedef boost::shared_ptr< ::fisheye_camera_matrix::perspective_projectionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fisheye_camera_matrix::perspective_projectionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct perspective_projectionResponse_

typedef ::fisheye_camera_matrix::perspective_projectionResponse_<std::allocator<void> > perspective_projectionResponse;

typedef boost::shared_ptr< ::fisheye_camera_matrix::perspective_projectionResponse > perspective_projectionResponsePtr;
typedef boost::shared_ptr< ::fisheye_camera_matrix::perspective_projectionResponse const> perspective_projectionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fisheye_camera_matrix::perspective_projectionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fisheye_camera_matrix::perspective_projectionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace fisheye_camera_matrix

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::fisheye_camera_matrix::perspective_projectionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fisheye_camera_matrix::perspective_projectionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fisheye_camera_matrix::perspective_projectionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fisheye_camera_matrix::perspective_projectionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fisheye_camera_matrix::perspective_projectionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fisheye_camera_matrix::perspective_projectionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fisheye_camera_matrix::perspective_projectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74ca570665a40606dd930ab3deca3e02";
  }

  static const char* value(const ::fisheye_camera_matrix::perspective_projectionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74ca570665a40606ULL;
  static const uint64_t static_value2 = 0xdd930ab3deca3e02ULL;
};

template<class ContainerAllocator>
struct DataType< ::fisheye_camera_matrix::perspective_projectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fisheye_camera_matrix/perspective_projectionResponse";
  }

  static const char* value(const ::fisheye_camera_matrix::perspective_projectionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fisheye_camera_matrix::perspective_projectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point p\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::fisheye_camera_matrix::perspective_projectionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fisheye_camera_matrix::perspective_projectionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.p);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct perspective_projectionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fisheye_camera_matrix::perspective_projectionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fisheye_camera_matrix::perspective_projectionResponse_<ContainerAllocator>& v)
  {
    s << indent << "p: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.p);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FISHEYE_CAMERA_MATRIX_MESSAGE_PERSPECTIVE_PROJECTIONRESPONSE_H
